const cfg = window.VAL_CONFIG || {};
const page = location.pathname.split('/').pop().replace('.html','') || 'index';

const data = {
  catalog:{title:'Каталог материалов',intro:'Выберите направление — затем мы подберём конкретную фактуру и рисунок под ваш проект.',html:'<div class="cards"><article class="card"><div class="photo photo1"></div><div class="body"><h3>Тёплый минимализм</h3><p>Спокойная фактура для жилых интерьеров.</p><div class="price">от 1 900 ₽/м²</div></div></article><article class="card"><div class="photo photo2"></div><div class="body"><h3>Архитектурная геометрия</h3><p>Выразительный рисунок для акцентной стены.</p><div class="price">от 2 100 ₽/м²</div></div></article><article class="card"><div class="photo photo3"></div><div class="body"><h3>Премиальная текстура</h3><p>Фактурные решения для дорогих интерьеров.</p><div class="price">от 2 300 ₽/м²</div></div></article></div>'},
  collections:{title:'Коллекции',intro:'Коллекции можно постепенно наполнять реальными материалами и фотографиями.',html:'<div class="cards"><article class="card"><div class="photo photo4"></div><div class="body"><h3>PURE</h3><p>Чистые формы и спокойная палитра.</p><a class="btn" href="contacts.html#form">Подобрать</a></div></article><article class="card"><div class="photo photo5"></div><div class="body"><h3>ART</h3><p>Выразительные композиции и акценты.</p><a class="btn" href="contacts.html#form">Подобрать</a></div></article></div>'},
  designers:{title:'Для дизайнеров',intro:'Партнёрская программа для дизайнеров и студий.',html:'<div class="grid3"><article><b>01</b><h3>Каталог образцов</h3><p>Помогаем быстро подобрать решение под концепцию проекта.</p></article><article><b>02</b><h3>Расчёт проекта</h3><p>Считаем площадь и готовим коммерческое предложение.</p></article><article><b>03</b><h3>Сопровождение</h3><p>Один контакт от подбора до заказа.</p></article></div><p><a class="btn" href="contacts.html#form">Стать партнёром</a></p>'},
  showroom:{title:'Шоурум',intro:'Живые материалы, фактуры и консультация.',html:'<div class="section-inner"><h2>Посмотрите материал вживую</h2><p>Здесь позже добавим адрес, фотографии, график работы и карту.</p><a class="btn" href="contacts.html#form">Записаться</a></div>'},
  order:{title:'Как заказать',intro:'Простой путь от фотографии стены до готового заказа.',html:'<div class="grid3"><article><b>01</b><h3>Отправьте размеры</h3><p>Укажите ширину и высоту стены.</p></article><article><b>02</b><h3>Получите подборку</h3><p>Мы предложим материалы и предварительный расчёт.</p></article><article><b>03</b><h3>Оформляем заказ</h3><p>Согласовываем детали и передаём заказ в работу.</p></article></div><p><a class="btn" href="contacts.html#form">Получить расчёт</a></p>'},
  about:{title:'О VAL',intro:'Бренд бесшовных решений для цельного интерьера.',html:'<div class="section-inner"><h2>Мы создаём не просто покрытие стены, а ощущение цельного пространства.</h2><p>Здесь постепенно разместим историю бренда, ценности, фотографии и преимущества.</p></div>'},
  contacts:{title:'Предварительный расчёт',intro:'Укажите размеры стены — калькулятор сразу покажет ориентировочную стоимость. Итог подтверждается после уточнения материала и проекта.',html:'<div class="calc-wrap"><form id="calcForm" class="form"><label>Ширина стены, м<input id="w" type="number" min="0.1" step="0.01" required placeholder="Например, 4.20"></label><label>Высота стены, м<input id="h" type="number" min="0.1" step="0.01" required placeholder="Например, 2.70"></label><label>Цена материала, ₽/м²<input id="price" type="number" min="1" step="1" value="1900" required></label><label>Запас на подрезку<input id="reserve" type="number" min="0" max="30" step="1" value="10"></label><button class="btn" type="submit">Рассчитать</button></form><div id="estimate" class="estimate"><span>Предварительный расчёт</span><strong id="result">Введите размеры</strong><small>Расчёт ориентировочный и не является публичной офертой.</small></div></div><hr class="divider"><h2>Отправить заявку</h2><form id="form" class="form"><input name="name" placeholder="Ваше имя" required><input name="phone" placeholder="Телефон / Telegram / WhatsApp" required><input name="area" id="area" placeholder="Площадь, м²" readonly><textarea name="message" placeholder="Коллекция, пожелания, комментарий"></textarea><button class="btn" type="submit">Получить расчёт и отправить заявку</button><p id="sent"></p></form>'}
};
const c=data[page];
if(c && document.getElementById('content')) document.getElementById('content').innerHTML=`<p style="max-width:700px;color:var(--muted);font-size:18px">${c.intro}</p>${c.html}`;

function money(n){return new Intl.NumberFormat('ru-RU').format(Math.round(n))+' ₽'}
function initCalc(){const f=document.getElementById('calcForm');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const w=+document.getElementById('w').value,h=+document.getElementById('h').value,p=+document.getElementById('price').value,r=+document.getElementById('reserve').value;const area=w*h,charge=area*(1+r/100),total=charge*p;document.getElementById('result').textContent=`${money(total)} · площадь ${area.toFixed(2)} м²`;const a=document.getElementById('area');if(a)a.value=area.toFixed(2);window.VAL_LAST_ESTIMATE={area,charge,total};});}
async function saveLead(e){e.preventDefault();const f=e.target;const payload=Object.fromEntries(new FormData(f).entries());payload.date=new Date().toISOString();payload.estimate=window.VAL_LAST_ESTIMATE||null;try{const res=await fetch('/.netlify/functions/lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error('network');document.getElementById('sent').textContent='Заявка отправлена. Мы свяжемся с вами.';f.reset();}catch(err){const leads=JSON.parse(localStorage.getItem('val_leads')||'[]');leads.push(payload);localStorage.setItem('val_leads',JSON.stringify(leads));document.getElementById('sent').textContent='Заявка сохранена в этом браузере. Для онлайн-отправки подключим Telegram на следующем этапе.';}}
function initForm(){const f=document.getElementById('form');if(f)f.addEventListener('submit',saveLead)}
initCalc();initForm();
